site_name: SwarmSwIM Documentation
theme:
  name: material

plugins:
  - search
  - mike

nav:
  - Home: Home.md
  - Getting Started: getting_started.md
  - Parameters: Parameters.md
  - Simulator: Simulator.md
  - Agent: Agent.md
  - CNN Detection: CNNDetection.md
  - XML Files: XML_files.md
