site_name: SwarmSwIM Documentation
theme:
  name: material
  # optional nice-to-have features
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate

plugins:
  - search

nav:
  - Home: index.md
  - Detection: CNNDetection.md
  - Parameters: Parameters.md
  - Plugin: Plugin_template.md
  - Simulator: Simulator.md
  - XML: XML_files.md
  - Agent: agent.md
  - Getting Started: getting_started.md
  - Installation: installation.md
  - Create New: create_new.md
  - Set Visualizer: setVisualizer.md
  - Set simulaiont xml: set_simulation_xml.md

docs_dir: docs