site_name: SwarmSwIM Documentation
theme:
  name: material
  # optional nice-to-have features
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - palette
    
  palette:
  - scheme: slate   # dark first
    primary: indigo
    accent: indigo
    toggle:
      icon: material/brightness-7
      name: Switch to light mode

  - scheme: default  # light alternative
    primary: indigo
    accent: indigo
    toggle:
      icon: material/brightness-4
      name: Switch to dark mode



plugins:
  - search

nav:
  - Home: index.md
  - Detection: CNNDetection.md
  - Parameters: Parameters.md
  - Plugin: Plugin_template.md
  - Simulator: Simulator.md
  - XML: XML_files.md
  - Agent: agent.md
  - Getting Started: getting_started.md
  - Installation: installation.md
  - Create New: create_new.md
  - Set Visualizer: setVisualizer.md
  - Set simulaiont xml: set_simulation_xml.md

docs_dir: docs